### PR TITLE
Avoid branches for bits types

### PR DESCRIPTION
**Pull request by johnmyleswhite**
This might resolve the SIMD problem seen by Jacob Quinn by removing a branch.

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
This PR potentially closes #22:

``` jl

julia> using NullableArrays

julia> A = rand(Float64, 5_000)
5000-element Array{Float64,1}:
 0.295619
 0.442019
 0.697729
 0.768991
 0.308044
 0.474409
 0.310926
 0.18187 
 0.922813
 0.410064
 ⋮       
 0.886561
 0.604451
 0.861349
 0.996207
 0.299021
 0.680601
 0.612236
 0.899984
 0.18355 

julia> X = NullableArray(A)
5000-element NullableArrays.NullableArray{Float64,1}:
 Nullable(0.2956185640383071) 
 Nullable(0.4420188559870306) 
 Nullable(0.6977285415172616) 
 Nullable(0.7689912300039385) 
 Nullable(0.30804399173516095)
 Nullable(0.47440908968517115)
 Nullable(0.3109263129940354) 
 Nullable(0.18186991033146627)
 Nullable(0.9228134615542094) 
 Nullable(0.41006395298879283)
 ⋮                            
 Nullable(0.8865608886699656) 
 Nullable(0.6044508315049326) 
 Nullable(0.8613489754657384) 
 Nullable(0.9962074618446397) 
 Nullable(0.2990205232481222) 
 Nullable(0.680601043977068)  
 Nullable(0.6122363334993455) 
 Nullable(0.8999842927990187) 
 Nullable(0.1835500184618939) 

julia> function f(X::NullableArray)
           res = 0.0
           @simd for i in 1:length(X)
               @inbounds res += X[i].value
           end
           return res
       end
f (generic function with 1 method)

julia> @code_llvm(f(X))

define double @julia_f_21672(%jl_value_t*) {
L:
  %1 = alloca [3 x %jl_value_t*], align 8
  %.sub = getelementptr inbounds [3 x %jl_value_t*]* %1, i64 0, i64 0
  %2 = getelementptr [3 x %jl_value_t*]* %1, i64 0, i64 2
  store %jl_value_t* inttoptr (i64 2 to %jl_value_t*), %jl_value_t** %.sub, align 8
  %3 = load %jl_value_t*** @jl_pgcstack, align 8
  %4 = getelementptr [3 x %jl_value_t*]* %1, i64 0, i64 1
  %.c = bitcast %jl_value_t** %3 to %jl_value_t*
  store %jl_value_t* %.c, %jl_value_t** %4, align 8
  store %jl_value_t** %.sub, %jl_value_t*** @jl_pgcstack, align 8
  store %jl_value_t* null, %jl_value_t** %2, align 8
  %5 = getelementptr inbounds %jl_value_t* %0, i64 0, i32 0
  %6 = load %jl_value_t** %5, align 8
  %7 = getelementptr inbounds %jl_value_t* %6, i64 1
  %8 = bitcast %jl_value_t* %7 to i64*
  %9 = load i64* %8, align 8
  %10 = icmp sgt i64 %9, 0
  %11 = select i1 %10, i64 %9, i64 0
  %12 = call { i64, i1 } @llvm.ssub.with.overflow.i64(i64 %11, i64 1)
  %13 = extractvalue { i64, i1 } %12, 1
  br i1 %13, label %fail, label %pass

fail:                                             ; preds = %L
  %14 = load %jl_value_t** @jl_overflow_exception, align 8
  call void @jl_throw_with_superfluous_argument(%jl_value_t* %14, i32 67)
  unreachable

pass:                                             ; preds = %L
  %15 = extractvalue { i64, i1 } %12, 0
  %16 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %15, i64 1)
  %17 = extractvalue { i64, i1 } %16, 1
  br i1 %17, label %fail1, label %pass2

fail1:                                            ; preds = %pass
  %18 = load %jl_value_t** @jl_overflow_exception, align 8
  call void @jl_throw_with_superfluous_argument(%jl_value_t* %18, i32 67)
  unreachable

pass2:                                            ; preds = %pass
  %19 = extractvalue { i64, i1 } %16, 0
  %20 = icmp slt i64 %19, 1
  br i1 %20, label %L21, label %if3

if3:                                              ; preds = %pass2
  %21 = load %jl_value_t** %5, align 8
  %22 = bitcast %jl_value_t* %21 to i8**
  %23 = load i8** %22, align 8
  %24 = bitcast i8* %23 to double*
  %n.vec = and i64 %19, -16
  %cmp.zero = icmp eq i64 %n.vec, 0
  br i1 %cmp.zero, label %middle.block, label %vector.body

vector.body:                                      ; preds = %vector.body, %if3
  %index = phi i64 [ %index.next, %vector.body ], [ 0, %if3 ]
  %vec.phi = phi <4 x double> [ %33, %vector.body ], [ zeroinitializer, %if3 ]
  %vec.phi25 = phi <4 x double> [ %34, %vector.body ], [ zeroinitializer, %if3 ]
  %vec.phi26 = phi <4 x double> [ %35, %vector.body ], [ zeroinitializer, %if3 ]
  %vec.phi27 = phi <4 x double> [ %36, %vector.body ], [ zeroinitializer, %if3 ]
  %25 = getelementptr double* %24, i64 %index
  %26 = bitcast double* %25 to <4 x double>*
  %wide.load = load <4 x double>* %26, align 8
  %.sum41 = or i64 %index, 4
  %27 = getelementptr double* %24, i64 %.sum41
  %28 = bitcast double* %27 to <4 x double>*
  %wide.load28 = load <4 x double>* %28, align 8
  %.sum42 = or i64 %index, 8
  %29 = getelementptr double* %24, i64 %.sum42
  %30 = bitcast double* %29 to <4 x double>*
  %wide.load29 = load <4 x double>* %30, align 8
  %.sum43 = or i64 %index, 12
  %31 = getelementptr double* %24, i64 %.sum43
  %32 = bitcast double* %31 to <4 x double>*
  %wide.load30 = load <4 x double>* %32, align 8
  %33 = fadd <4 x double> %vec.phi, %wide.load
  %34 = fadd <4 x double> %vec.phi25, %wide.load28
  %35 = fadd <4 x double> %vec.phi26, %wide.load29
  %36 = fadd <4 x double> %vec.phi27, %wide.load30
  %index.next = add i64 %index, 16
  %37 = icmp eq i64 %index.next, %n.vec
  br i1 %37, label %middle.block, label %vector.body

middle.block:                                     ; preds = %vector.body, %if3
  %resume.val = phi i64 [ 0, %if3 ], [ %n.vec, %vector.body ]
  %rdx.vec.exit.phi = phi <4 x double> [ zeroinitializer, %if3 ], [ %33, %vector.body ]
  %rdx.vec.exit.phi33 = phi <4 x double> [ zeroinitializer, %if3 ], [ %34, %vector.body ]
  %rdx.vec.exit.phi34 = phi <4 x double> [ zeroinitializer, %if3 ], [ %35, %vector.body ]
  %rdx.vec.exit.phi35 = phi <4 x double> [ zeroinitializer, %if3 ], [ %36, %vector.body ]
  %bin.rdx = fadd <4 x double> %rdx.vec.exit.phi33, %rdx.vec.exit.phi
  %bin.rdx36 = fadd <4 x double> %rdx.vec.exit.phi34, %bin.rdx
  %bin.rdx37 = fadd <4 x double> %rdx.vec.exit.phi35, %bin.rdx36
  %rdx.shuf = shufflevector <4 x double> %bin.rdx37, <4 x double> undef, <4 x i32> <i32 2, i32 3, i32 undef, i32 undef>
  %bin.rdx38 = fadd <4 x double> %bin.rdx37, %rdx.shuf
  %rdx.shuf39 = shufflevector <4 x double> %bin.rdx38, <4 x double> undef, <4 x i32> <i32 1, i32 undef, i32 undef, i32 undef>
  %bin.rdx40 = fadd <4 x double> %bin.rdx38, %rdx.shuf39
  %38 = extractelement <4 x double> %bin.rdx40, i32 0
  %cmp.n = icmp eq i64 %19, %resume.val
  br i1 %cmp.n, label %L21, label %L5

L5:                                               ; preds = %L5, %middle.block
  %"##i#9126.0" = phi i64 [ %42, %L5 ], [ %resume.val, %middle.block ]
  %res.1 = phi double [ %41, %L5 ], [ %38, %middle.block ]
  %39 = getelementptr double* %24, i64 %"##i#9126.0"
  %40 = load double* %39, align 8
  %41 = fadd fast double %res.1, %40
  %42 = add i64 %"##i#9126.0", 1
  %exitcond = icmp eq i64 %42, %19
  br i1 %exitcond, label %L21, label %L5

L21:                                              ; preds = %L5, %middle.block, %pass2
  %res.3 = phi double [ 0.000000e+00, %pass2 ], [ %41, %L5 ], [ %38, %middle.block ]
  %43 = load %jl_value_t** %4, align 8
  %44 = getelementptr inbounds %jl_value_t* %43, i64 0, i32 0
  store %jl_value_t** %44, %jl_value_t*** @jl_pgcstack, align 8
  ret double %res.3
}

julia> 
```

**Comment by johnmyleswhite** [comment]
With a change to Base, we should be able to get SIMD magic even without going right into the `.value` field of a `Nullable`.

**Comment by davidagold** [comment]
Nice.

Given that your fix does have a branch in it, might we say that branching per se is not the problem, but rather branching that may return either an empty or a non-empty `Nullable{T}` object?

**Comment by johnmyleswhite** [comment]
It's unfortunately more complicated than that: what's happening here is that the outer branch is completely evaluated at compile-time and therefore removed from the code, leaving no branch at all when `T` is a bits-type.

This is counter-intuitive, but you need a branch to remove all branching.

**Comment by davidagold** [comment]
Hah! That does makes sense, though, since treatment of that branch is
amenable to static analysis of the argument types. I didn't realize that
such optimizations take place.

**Comment by johnmyleswhite** [comment]
They do, although they're very hard to predict.

**Comment by nalimilan** [comment]
Great!

**Pull request merged**
