### PR TITLE
importall Base.Operators

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
FWIW, I'd be more in favor of explicitly qualifying all operators.

**Comment by quinnj** [comment]
That's cool. I think it was mainly `>=`, `<=`, `==` that I was seeing, so this was my quick fix. Probably easier for you or David to just push the fix.

**Comment by davidagold** [comment]
Done https://github.com/johnmyleswhite/NullableArrays.jl/pull/54

**Comment by quinnj** [comment]
Thanks David.

**Pull request closed without merging**
