### PR TITLE
Fix deprecation of $ as xor()

### PR DESCRIPTION
**Pull request by nalimilan**

### CODE REVIEW

**Review by ararslan — APPROVED** [review]
Who knows what's going on with AppVeyor. This looks good to me, and Travis seems to agree.

**Comment by nalimilan** [comment]
There's something weird with AppVeyor, it always starts twice, and the first build fails because a newer one is queued. When the second build is done, it turns green. Never seen this in other projects, so the configuration must be incorrect.

**Comment by nalimilan** [comment]
Turns out the webhook was set up twice...

**Comment by ararslan** [comment]
Weird. Were you able to fix that?

**Pull request merged**
