### PR TITLE
Fixed world issue on `lift` (depending on `null_safe_op`) when `compilecache=no`

### PR DESCRIPTION
**Pull request by rofinn**
Example)
```shell
~/repos > julia --compilecache=no -e 'Pkg.test("NullableArrays")'                                         13:17:14
INFO: Testing NullableArrays
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /Users/rory/.julia/v0.6/NullableArrays/src/operators.jl:128.
Running tests:
	PASSED: typedefs.jl
	PASSED: constructors.jl
	PASSED: primitives.jl
	PASSED: indexing.jl
	FAILED: map.jl
LoadError: MethodError: no method matching null_safe_op(::TestMap.#f, ::Type{Float64})
You may have intended to import Base.null_safe_op
The applicable method may be too new: running in world age 24412, while current world is 24744.
Closest candidates are:
  null_safe_op(::Any, ::Type...) at /Users/rory/.julia/v0.6/NullableArrays/src/operators.jl:39 (method too new to be called from this world context.)
  null_safe_op(!Matched::Base.#+, ::Type{S<:Union{Float16, Float32, Float64}}, !Matched::Type{T<:Union{Float16, Float32, Float64}}) where {S<:Union{Float16, Float32, Float64}, T<:Union{Float16, Float32, Float64}} at /Users/rory/.julia/v0.6/NullableArrays/src/operators.jl:99 (method too new to be called from this world context.)
  null_safe_op(!Matched::Base.#+, ::Type{S<:Union{Float16, Float32, Float64, Int128, Int16, Int32, Int64, Int8}}, !Matched::Type{T<:Union{Float16, Float32, Float64, Int128, Int16, Int32, Int64, Int8}}) where {S<:Union{Float16, Float32, Float64, Int128, Int16, Int32, Int64, Int8}, T<:Union{Float16, Float32, Float64, Int128, Int16, Int32, Int64, Int8}} at /Users/rory/.julia/v0.6/NullableArrays/src/operators.jl:101 (method too new to be called from this world context.)
  ...
Stacktrace:
 [1] macro expansion at /Users/rory/.julia/v0.6/NullableArrays/test/runtests.jl:35 [inlined]
 [2] anonymous at ./<missing>:?
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] include(::String) at ./sysimg.jl:14
 [5] process_options(::Base.JLOptions) at ./client.jl:305
 [6] _start() at ./client.jl:371
while loading /Users/rory/.julia/v0.6/NullableArrays/test/map.jl, in expression starting on line 32
	FAILED: broadcast.jl
LoadError: MethodError: no method matching null_safe_op(::TestBroadcast.#f, ::Type{Int64})
You may have intended to import Base.null_safe_op
The applicable method may be too new: running in world age 24412, while current world is 24757.
Closest candidates are:
  null_safe_op(::Any, ::Type...) at /Users/rory/.julia/v0.6/NullableArrays/src/operators.jl:39 (method too new to be called from this world context.)
  null_safe_op(!Matched::Base.#+, ::Type{S<:Union{Float16, Float32, Float64, Int128, Int16, Int32, Int64, Int8}}, !Matched::Type{T<:Union{Float16, Float32, Float64, Int128, Int16, Int32, Int64, Int8}}) where {S<:Union{Float16, Float32, Float64, Int128, Int16, Int32, Int64, Int8}, T<:Union{Float16, Float32, Float64, Int128, Int16, Int32, Int64, Int8}} at /Users/rory/.julia/v0.6/NullableArrays/src/operators.jl:101 (method too new to be called from this world context.)
  null_safe_op(!Matched::Base.#+, ::Type{T<:Union{Bool, Float16, Float32, Float64, Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}}) where T<:Union{Bool, Float16, Float32, Float64, Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at /Users/rory/.julia/v0.6/NullableArrays/src/operators.jl:58 (method too new to be called from this world context.)
  ...
Stacktrace:
 [1] macro expansion at /Users/rory/.julia/v0.6/NullableArrays/test/runtests.jl:35 [inlined]
 [2] anonymous at ./<missing>:?
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] include(::String) at ./sysimg.jl:14
 [5] process_options(::Base.JLOptions) at ./client.jl:305
 [6] _start() at ./client.jl:371
while loading /Users/rory/.julia/v0.6/NullableArrays/test/broadcast.jl, in expression starting on line 39
	PASSED: nullablevector.jl
	PASSED: nullablematrix.jl
	PASSED: reduce.jl
	PASSED: operators.jl
	PASSED: subarray.jl
	PASSED: show.jl
Test Summary: | Pass  Total
describe      |   10     10
	PASSED: utils.jl
ERROR: LoadError: "Tests failed"
```

### CODE REVIEW

**Comment by rofinn** [comment]
CI fails on 0.7 because we're generating too many deprecation warnings.

**Comment by spurll** [comment]
It seems to me like that shouldn't be a dealbreaker.

**Comment by rofinn** [comment]
I'm inclined to:

1. Merge #201 so that we bring the appveyor build time down to 5min (from > 1hr)
2. Add a PR that allows travis failures on nightly
3. Merge this if travis still passes after that.

**Comment by ararslan** [comment]
Close and reopen: The poor man's rebase.

**Comment by ararslan** [comment]
...except it seems not to have retriggered CI.

**Comment by rofinn** [comment]
Alright, I'll rebase locally and push.

**Comment by rofinn** [comment]
Weird, that also didn't trigger a new build...?

**Comment by ararslan** [comment]
Seems to have finally triggered. Something's up with Travis today; things are taking a while to trigger. Noticed it on another repo as well.

**Pull request merged**
