### PR TITLE
Fix missing Union{...} deprecation

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
Thanks!

**Comment by johnmyleswhite** [comment]
Hmm. This apparently failed, although I can't imagine why. Perhaps Travis cut it short when I merged it?

**Comment by simonster** [comment]
Looks like it's because the Julia nightlies were built without libssl support (https://github.com/JuliaLang/julia/issues/13389)

**Comment by simonster** [comment]
No actually it's a different error. Maybe something about the SSL config on Travis is interacting badly with libgit2, such that libgit2 doesn't have the proper root certificates?

**Comment by johnmyleswhite** [comment]
Sigh. False positive testing infra...

**Pull request merged**
